version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npm run generate && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
